[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"

[context.production]
  command = "hugo --minify"
  
[context.deploy-preview]
  command = "hugo --minify -D"
