name: Add Hugo Theme
on:
  workflow_dispatch:

jobs:
  add-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add PaperMod theme
        run: |
          git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add PaperMod theme"
          git push
