name: Add Hugo Theme

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]
 workflow_dispatch:

jobs:
 add-theme:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4
       with:
         token: ${{ secrets.GITHUB_TOKEN }}

     - name: Add PaperMod theme as submodule
       run: |
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git submodule add https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
         git add .
         git commit -m "Add PaperMod theme as git submodule"
         git push

     - name: Verify theme installation
       run: |
         echo "테마 설치 완료!"
         echo "다른 작업을 빌드에 추가하고,"
         echo "테스트하고 프로젝트를 배포하세요."
